apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: caiocaldeira
  name: project2-pv2-caiocaldeira
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: default-storage-class
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/caiocaldeira/project2-pv2
