apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-caiocaldeira
  labels:
    namespace: caiocaldeira
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: caiocadeira
