apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
  namespace: caiocaldeira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server-container
          image: quay.io/caiocaldeira/server-container:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_PATH
              value: /project2-pv2/rules.pkl
          volumeMounts:
            - name: server-volume
              mountPath: /project2-pv2
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: project2-pv2-caiocaldeira
