apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-caiocaldeira
  namespace: caiocaldeira
spec:
  storageClassName: default-storage-class-caiocaldeira
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: caiocaldeira
