apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  namespace: caiocaldeira
spec:
  selector:
    app: playlist-recommender
    role: server
  ports:
    port: 52007
    nodePort: 52007
    targetPort: 5000
  type: NodePort
