apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  labels:
    app: playlist-recommender
spec:
  selector:
    app: playlist-recommender
    role: server
  ports:
  - protocol: HTTP
    port: 52007
    nodePort: 52007
    targetPort: 5000
  type: NodePort
