apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  namespace: caiocaldeira
spec:
  selector:
    app: playlist-recommender
  ports:
    - name: http
      port: 52007
      targetPort: 5000
      nodePort: 52007
  type: NodePort
